title: Hongjie Jiang's Homepage
page-top-title: Hongjie Jiang
top-section-bg-text: Every heart has stars.
home-subtitle: Hongjie Jiang&ensp;|&ensp;蒋弘杰
copyright-text: '&copy; Hongjie Jiang 2025. All Rights Reserved.'
